name: Docker Image CI

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build BLE Image
      run: docker build . --file Dockerfile --tag hiflow-ble-mqtt:$(date +%s)
    
    - name: Build webui Image
      run: docker build . --file Dockerfile.web --tag hiflow-web-mqtt:$(date +%s)
